### PR TITLE
[Feature] Japanese Localization

### PR DESCRIPTION
**Pull request by tockrock**
Thanks for this project!
I've also referenced Apple's localization.
Hopes this helps.

### CODE REVIEW

**Review by FelixHerrmann — APPROVED** [review]
Thanks for your contribution, looks good to me!

**Comment by FelixHerrmann** [comment]
@tockrock please resolve the lint error, then we can get this in!

**Comment by tockrock** [comment]
Thanks for the fix & merge!

**Comment by FelixHerrmann** [comment]
No problem, will make a release soon!

**Pull request merged**
